config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  resources :tweets, only: [:index] do
    get :search, on: :collection
    get :mentionners, on: :collection
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  default_scope do
    order('user_followers_count desc,
          retweet_count desc,
          favourites_count desc')
  end

  def self.top_mentioners
  all
      .group_by(&:user_screen_name)
      .sort_by { |_user, tweets| [tweets.count, tweets.map(&:user_followers_count)] }
      .reverse
      .collect { |users_tweets| users_tweets.last }
      .flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all || search
  end

  def search
    @tweets = TweetBuilder.save
    redirect_to tweets_path
  end

  def mentionners
    @tweets = Tweet.top_mentioners
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_date(date)
    date.blank? ? '' : date.strftime('%d/%m/%Y %m:%H')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterSac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Twitter SAC', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Top Mencionadores', mentionners_tweets_path %></li>
          <li><%= link_to 'Novas Menções', search_tweets_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/tweets/_tweet.html.erb
<tr id="tweet_<%= tweet.id %>">
  <td><%= link_to tweet.user_screen_name, "//twitter.com/#{tweet.user_screen_name}", target: '_blank' %></td>
  <td><%= tweet.user_followers_count %></td>
  <td><%= tweet.text %></td>
  <td><%= tweet.retweet_count %></td>
  <td><%= tweet.favourites_count %></td>
  <td><%= link_to human_date(tweet.tweeted_at), "//twitter.com/#{tweet.user_screen_name}", target: '_blank' %></td>
</tr>

app/views/tweets/index.html.erb
<div>
  <h1>Menções</h1>
  <table id='tweets' class='table table-bordered table-striped'>
    <tr>
      <th>Usuário</th>
      <th>Seguidores</th>
      <th>Tweet (<%= @tweets.count %>)</th>
      <th>RTs</th>
      <th>Likes</th>
      <th>Data</th>
    </tr>
    <% if @tweets.any? %>
      <%= render @tweets %>
    <% else %>
      <tr>
       <td colspan='6'>Sem menções para analisar</td>
      </tr>
    <% end %>
  </table>
</div>

app/views/tweets/mentionners.html.erb
<div>
  <h1>Top Mencionadores</h1>
  <table id='tweets' class='table table-bordered table-striped'>
    <tr>
      <th>Usuário</th>
      <th>Seguidores</th>
      <th>Tweet</th>
      <th>RTs</th>
      <th>Likes</th>
      <th>Data</th>
    </tr>
    <% if @tweets.any? %>
      <%= render @tweets %>
    <% else %>
      <tr>
       <td colspan='6'>Sem menções para analisar</td>
      </tr>
    <% end %>
  </table>
</div>